package pkg

const template = `#  --- DO NOT EDIT --- AUTO-GENERATED-FILE ---
# autogenerated at time-here:

version: 0.0.1
releaseId:
commitId:
`

type VersionData struct {
	Version   VersionParsed
	ReleaseId string
	CommitId  string
}

type VersionParsed struct {
	Major      int
	Minor      int
	Patch      int
	Prerelease string // vM.m.p-{prerelease}
}

type BumpVersion int

const (
	_ BumpVersion = iota
	Major
	Minor
	Patch
)

func Version(data *VersionData, bump BumpVersion) error {
	switch bump {
	case Major:
		data.Version.Major++
		break
	case Minor:
		data.Version.Minor++
		break
	case Patch:
		data.Version.Patch++
		break
	}

	return nil
}

func updateTime() {

}
