name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  issues: write
  pull-requests: write
  contents: write
  packages: write

jobs:

  build:
    #    strategy:
    #      matrix:
    #        kind: [ 'linux', 'windows', 'macOS' ]
    #        include:
    #          - kind: linux
    #            os: ubuntu-latest
    #            target: linux-x64
    #            release_suffix: ''
    #          - kind: windows
    #            os: windows-latest
    #            target: win-x64
    #            release_suffix: .exe
    #          - kind: macOS
    #            os: macos-latest
    #            target: osx-x64
    #            release_suffix: ''

    runs-on: ubuntu-20.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o ./build/bebop

      #    - name: Test
      #      run: go test -v ./...

      - name: Bump version
        id: bump_version
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commitId=$(git show -s --format=%H)
          releaseId=${{ github.run_id }}
          
          version=$(./build/bebop project version --bump patch --release-file ./release.yml --releaseId ${releaseId} --commitId ${commitId})
          
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"          
          git commit -am "Bump version"
          git push 
          
          echo ::set-output name=release_version::${version}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ steps.bump_version.outputs.release_version }}
          name: ${{ steps.bump_version.outputs.release_version }}

#      - name: Create release (master only)
#        id: create-release
#        if: github.ref == 'refs/heads/main'
#        uses: actions/create-release@v1
#        continue-on-error: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.bump_version.outputs.release_version }}
#          release_name: ${{ steps.bump_version.outputs.release_version }}
