name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  issues: write
  pull-requests: write

jobs:

  build:
    #    strategy:
    #      matrix:
    #        kind: [ 'linux', 'windows', 'macOS' ]
    #        include:
    #          - kind: linux
    #            os: ubuntu-latest
    #            target: linux-x64
    #            release_suffix: ''
    #          - kind: windows
    #            os: windows-latest
    #            target: win-x64
    #            release_suffix: .exe
    #          - kind: macOS
    #            os: macos-latest
    #            target: osx-x64
    #            release_suffix: ''

    runs-on: ubuntu-20.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o ./build/bebop

      #    - name: Test
      #      run: go test -v ./...

      #    - uses: rymndhng/release-on-push-action@master
      #      with:
      #        tag_prefix: "v"
      #        bump_version_scheme: minor
      - name: Create release (master only)
        id: create-release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          release_name: test-release
